services:
  app:
    image: unit:php8.4
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www
      - ./backend/config.json:/docker-entrypoint.d/config.json
    depends_on:
      - db
  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: backend
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
